minimumReleaseAge: 360
saveExact: true
strictPeerDependencies: true
updateNotifier: false
allowBuilds:
  esbuild: true
  simple-git-hooks: true

# Vite+ setup
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.21-alpha.6
  vite-plus: 0.1.21-alpha.6
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.21-alpha.6
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
